Post sobre claves y dotfiles y yubikeys
lugfi/lugfi.github.io pull request #44
Opened 2017-09-08 13:17 UTC by tinchou

2017-09-09 00:05 UTC, AlexDaciuk requested changes

2017-09-09 00:05 UTC, AlexDaciuk commented on _posts/2017-09-08-claves_dotfiles_y_yubikeys.md
> +Si tuviera una Yubikey moderna (con NFC), el problema sería trivial ya que existe el software adecuado. Hice pruebas conectándola al puerto USB-C sin éxito, pero es posible que sea cuestión de encont
Acá te falta actualizar con lo de OpenKeyChain, según entendí lo hiciste funcionar

2017-09-10 23:25 UTC, tinchou commented
Ping

2017-09-11 01:32 UTC, AlexDaciuk approved these changes

2017-09-11 01:33 UTC, AlexDaciuk commented
Para mi esta bien, podes mergear si queres, estaria copado un post hablando un toque de la yubi, parece re magico en tu post ...

Esta semana me pongo a hacer un post sobre KeePassXC ...

2017-09-11 12:44 UTC, tinchou commented
Se puede, pero es un hardware cerrado y no me parece que deba ser el foco

2017-09-11 17:25 UTC, fbarrios approved these changes

2017-09-11 17:39 UTC, merged

2017-09-11 17:39 UTC, tinchou commented
@fbarrios @AlexDaciuk cracks